# Generated by Django 4.2.3 on 2024-05-10 04:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesDetails',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('recipe_title', models.CharField(max_length=50)),
                ('recipe_description', models.TextField()),
                ('recipe_created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_ratings', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountdetails')),
            ],
        ),
    ]
